set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR armv7)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_OSX_ARCHITECTURES "" CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "" FORCE)
set(CMAKE_OSX_SYSROOT "" CACHE STRING "" FORCE)

# CMake reloads this toolchain inside compiler ABI try_compile projects. Custom
# cache variables are not forwarded to those child configures unless they are
# named here, so the child used to lose POWERENGINE_ROOT/VIRTUA_LLVM_ROOT and
# fail before it could identify the compiler.
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    POWERENGINE_ROOT
    VIRTUA_LLVM_ROOT
    VIRTUA_ARM_SYSROOT
    VIRTUA_ARM_COMPILER_RT
    VIRTUA_ARM_TARGET_TRIPLE)
list(REMOVE_DUPLICATES CMAKE_TRY_COMPILE_PLATFORM_VARIABLES)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    "${CMAKE_TRY_COMPILE_PLATFORM_VARIABLES}" CACHE STRING
    "Virtua ARM variables propagated into CMake try_compile projects" FORCE)

include("${CMAKE_CURRENT_LIST_DIR}/VirtuaPowerEngine.cmake")

set(CMAKE_C_COMPILER "${VIRTUA_CLANG_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${VIRTUA_CLANGXX_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${VIRTUA_CLANG_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_TARGET "${VIRTUA_ARM_TARGET_TRIPLE}" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET "${VIRTUA_ARM_TARGET_TRIPLE}" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER_TARGET "${VIRTUA_ARM_TARGET_TRIPLE}" CACHE STRING "" FORCE)
set(CMAKE_AR "${VIRTUA_AR_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${VIRTUA_RANLIB_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY "${VIRTUA_OBJCOPY_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER "${VIRTUA_LLD_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_SYSROOT "${VIRTUA_ARM_SYSROOT}" CACHE PATH "" FORCE)
set(CMAKE_FIND_ROOT_PATH "${VIRTUA_ARM_SYSROOT}" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
